module.exports = {
  "Microsoft Universal Principal Name": "msUPN",
  "Microsoft Smartcardlogin": "msSmartcardLogin",
  "itu-t": "ITU-T",
  "iso": "ISO",
  "joint-iso-itu-t": "JOINT-ISO-ITU-T",
  "ISO Member Body": "member-body",
  "identified-organization": "identified-organization",
  "hmac-md5": "HMAC-MD5",
  "hmac-sha1": "HMAC-SHA1",
  "Professional Information or basis for Admission": "x509ExtAdmission",
  "certicom-arc": "certicom-arc",
  "ieee": "ieee",
  "IEEE Security in Storage Working Group": "ieee-siswg",
  "International Organizations": "international-organizations",
  "wap": "wap",
  "wap-wsg": "wap-wsg",
  "Selected Attribute Types": "selected-attribute-types",
  "clearance": "clearance",
  "ISO US Member Body": "ISO-US",
  "X9.57": "X9-57",
  "X9.57 CM ?": "X9cm",
  "ISO CN Member Body": "ISO-CN",
  "oscca": "oscca",
  "sm-scheme": "sm-scheme",
  "dsaEncryption": "DSA",
  "dsaWithSHA1": "DSA-SHA1",
  "ANSI X9.62": "ansi-X9-62",
  "prime-field": "prime-field",
  "characteristic-two-field": "characteristic-two-field",
  "id-characteristic-two-basis": "id-characteristic-two-basis",
  "onBasis": "onBasis",
  "tpBasis": "tpBasis",
  "ppBasis": "ppBasis",
  "id-ecPublicKey": "id-ecPublicKey",
  "c2pnb163v1": "c2pnb163v1",
  "c2pnb163v2": "c2pnb163v2",
  "c2pnb163v3": "c2pnb163v3",
  "c2pnb176v1": "c2pnb176v1",
  "c2tnb191v1": "c2tnb191v1",
  "c2tnb191v2": "c2tnb191v2",
  "c2tnb191v3": "c2tnb191v3",
  "c2onb191v4": "c2onb191v4",
  "c2onb191v5": "c2onb191v5",
  "c2pnb208w1": "c2pnb208w1",
  "c2tnb239v1": "c2tnb239v1",
  "c2tnb239v2": "c2tnb239v2",
  "c2tnb239v3": "c2tnb239v3",
  "c2onb239v4": "c2onb239v4",
  "c2onb239v5": "c2onb239v5",
  "c2pnb272w1": "c2pnb272w1",
  "c2pnb304w1": "c2pnb304w1",
  "c2tnb359v1": "c2tnb359v1",
  "c2pnb368w1": "c2pnb368w1",
  "c2tnb431r1": "c2tnb431r1",
  "prime192v1": "prime192v1",
  "prime192v2": "prime192v2",
  "prime192v3": "prime192v3",
  "prime239v1": "prime239v1",
  "prime239v2": "prime239v2",
  "prime239v3": "prime239v3",
  "prime256v1": "prime256v1",
  "ecdsa-with-SHA1": "ecdsa-with-SHA1",
  "ecdsa-with-Recommended": "ecdsa-with-Recommended",
  "ecdsa-with-Specified": "ecdsa-with-Specified",
  "ecdsa-with-SHA224": "ecdsa-with-SHA224",
  "ecdsa-with-SHA256": "ecdsa-with-SHA256",
  "ecdsa-with-SHA384": "ecdsa-with-SHA384",
  "ecdsa-with-SHA512": "ecdsa-with-SHA512",
  "secp112r1": "secp112r1",
  "secp112r2": "secp112r2",
  "secp128r1": "secp128r1",
  "secp128r2": "secp128r2",
  "secp160k1": "secp160k1",
  "secp160r1": "secp160r1",
  "secp160r2": "secp160r2",
  "secp192k1": "secp192k1",
  "secp224k1": "secp224k1",
  "secp224r1": "secp224r1",
  "secp256k1": "secp256k1",
  "secp384r1": "secp384r1",
  "secp521r1": "secp521r1",
  "sect113r1": "sect113r1",
  "sect113r2": "sect113r2",
  "sect131r1": "sect131r1",
  "sect131r2": "sect131r2",
  "sect163k1": "sect163k1",
  "sect163r1": "sect163r1",
  "sect163r2": "sect163r2",
  "sect193r1": "sect193r1",
  "sect193r2": "sect193r2",
  "sect233k1": "sect233k1",
  "sect233r1": "sect233r1",
  "sect239k1": "sect239k1",
  "sect283k1": "sect283k1",
  "sect283r1": "sect283r1",
  "sect409k1": "sect409k1",
  "sect409r1": "sect409r1",
  "sect571k1": "sect571k1",
  "sect571r1": "sect571r1",
  "wap-wsg-idm-ecid-wtls1": "wap-wsg-idm-ecid-wtls1",
  "wap-wsg-idm-ecid-wtls3": "wap-wsg-idm-ecid-wtls3",
  "wap-wsg-idm-ecid-wtls4": "wap-wsg-idm-ecid-wtls4",
  "wap-wsg-idm-ecid-wtls5": "wap-wsg-idm-ecid-wtls5",
  "wap-wsg-idm-ecid-wtls6": "wap-wsg-idm-ecid-wtls6",
  "wap-wsg-idm-ecid-wtls7": "wap-wsg-idm-ecid-wtls7",
  "wap-wsg-idm-ecid-wtls8": "wap-wsg-idm-ecid-wtls8",
  "wap-wsg-idm-ecid-wtls9": "wap-wsg-idm-ecid-wtls9",
  "wap-wsg-idm-ecid-wtls10": "wap-wsg-idm-ecid-wtls10",
  "wap-wsg-idm-ecid-wtls11": "wap-wsg-idm-ecid-wtls11",
  "wap-wsg-idm-ecid-wtls12": "wap-wsg-idm-ecid-wtls12",
  "cast5-cbc": "CAST5-CBC",
  "cast5-ecb": "CAST5-ECB",
  "cast5-cfb": "CAST5-CFB",
  "cast5-ofb": "CAST5-OFB",
  "pbeWithMD5AndCast5CBC": "pbeWithMD5AndCast5CBC",
  "password based MAC": "id-PasswordBasedMAC",
  "Diffie-Hellman based MAC": "id-DHBasedMac",
  "RSA Data Security, Inc.": "rsadsi",
  "RSA Data Security, Inc. PKCS": "pkcs",
  "pkcs1": "pkcs1",
  "rsaEncryption": "rsaEncryption",
  "md2WithRSAEncryption": "RSA-MD2",
  "md4WithRSAEncryption": "RSA-MD4",
  "md5WithRSAEncryption": "RSA-MD5",
  "sha1WithRSAEncryption": "RSA-SHA1",
  "rsaesOaep": "RSAES-OAEP",
  "mgf1": "MGF1",
  "pSpecified": "PSPECIFIED",
  "rsassaPss": "RSASSA-PSS",
  "sha256WithRSAEncryption": "RSA-SHA256",
  "sha384WithRSAEncryption": "RSA-SHA384",
  "sha512WithRSAEncryption": "RSA-SHA512",
  "sha224WithRSAEncryption": "RSA-SHA224",
  "sha512-224WithRSAEncryption": "RSA-SHA512/224",
  "sha512-256WithRSAEncryption": "RSA-SHA512/256",
  "pkcs3": "pkcs3",
  "dhKeyAgreement": "dhKeyAgreement",
  "pkcs5": "pkcs5",
  "pbeWithMD2AndDES-CBC": "PBE-MD2-DES",
  "pbeWithMD5AndDES-CBC": "PBE-MD5-DES",
  "pbeWithMD2AndRC2-CBC": "PBE-MD2-RC2-64",
  "pbeWithMD5AndRC2-CBC": "PBE-MD5-RC2-64",
  "pbeWithSHA1AndDES-CBC": "PBE-SHA1-DES",
  "pbeWithSHA1AndRC2-CBC": "PBE-SHA1-RC2-64",
  "PBKDF2": "PBKDF2",
  "PBES2": "PBES2",
  "PBMAC1": "PBMAC1",
  "pkcs7": "pkcs7",
  "pkcs7-data": "pkcs7-data",
  "pkcs7-signedData": "pkcs7-signedData",
  "pkcs7-envelopedData": "pkcs7-envelopedData",
  "pkcs7-signedAndEnvelopedData": "pkcs7-signedAndEnvelopedData",
  "pkcs7-digestData": "pkcs7-digestData",
  "pkcs7-encryptedData": "pkcs7-encryptedData",
  "pkcs9": "pkcs9",
  "emailAddress": "emailAddress",
  "unstructuredName": "unstructuredName",
  "contentType": "contentType",
  "messageDigest": "messageDigest",
  "signingTime": "signingTime",
  "countersignature": "countersignature",
  "challengePassword": "challengePassword",
  "unstructuredAddress": "unstructuredAddress",
  "extendedCertificateAttributes": "extendedCertificateAttributes",
  "Extension Request": "extReq",
  "S/MIME Capabilities": "SMIME-CAPS",
  "S/MIME": "SMIME",
  "id-smime-mod": "id-smime-mod",
  "id-smime-ct": "id-smime-ct",
  "id-smime-aa": "id-smime-aa",
  "id-smime-alg": "id-smime-alg",
  "id-smime-cd": "id-smime-cd",
  "id-smime-spq": "id-smime-spq",
  "id-smime-cti": "id-smime-cti",
  "id-smime-mod-cms": "id-smime-mod-cms",
  "id-smime-mod-ess": "id-smime-mod-ess",
  "id-smime-mod-oid": "id-smime-mod-oid",
  "id-smime-mod-msg-v3": "id-smime-mod-msg-v3",
  "id-smime-mod-ets-eSignature-88": "id-smime-mod-ets-eSignature-88",
  "id-smime-mod-ets-eSignature-97": "id-smime-mod-ets-eSignature-97",
  "id-smime-mod-ets-eSigPolicy-88": "id-smime-mod-ets-eSigPolicy-88",
  "id-smime-mod-ets-eSigPolicy-97": "id-smime-mod-ets-eSigPolicy-97",
  "id-smime-ct-receipt": "id-smime-ct-receipt",
  "id-smime-ct-authData": "id-smime-ct-authData",
  "id-smime-ct-publishCert": "id-smime-ct-publishCert",
  "id-smime-ct-TSTInfo": "id-smime-ct-TSTInfo",
  "id-smime-ct-TDTInfo": "id-smime-ct-TDTInfo",
  "id-smime-ct-contentInfo": "id-smime-ct-contentInfo",
  "id-smime-ct-DVCSRequestData": "id-smime-ct-DVCSRequestData",
  "id-smime-ct-DVCSResponseData": "id-smime-ct-DVCSResponseData",
  "id-smime-ct-compressedData": "id-smime-ct-compressedData",
  "id-smime-ct-contentCollection": "id-smime-ct-contentCollection",
  "id-smime-ct-authEnvelopedData": "id-smime-ct-authEnvelopedData",
  "id-ct-asciiTextWithCRLF": "id-ct-asciiTextWithCRLF",
  "id-ct-xml": "id-ct-xml",
  "id-smime-aa-receiptRequest": "id-smime-aa-receiptRequest",
  "id-smime-aa-securityLabel": "id-smime-aa-securityLabel",
  "id-smime-aa-mlExpandHistory": "id-smime-aa-mlExpandHistory",
  "id-smime-aa-contentHint": "id-smime-aa-contentHint",
  "id-smime-aa-msgSigDigest": "id-smime-aa-msgSigDigest",
  "id-smime-aa-encapContentType": "id-smime-aa-encapContentType",
  "id-smime-aa-contentIdentifier": "id-smime-aa-contentIdentifier",
  "id-smime-aa-macValue": "id-smime-aa-macValue",
  "id-smime-aa-equivalentLabels": "id-smime-aa-equivalentLabels",
  "id-smime-aa-contentReference": "id-smime-aa-contentReference",
  "id-smime-aa-encrypKeyPref": "id-smime-aa-encrypKeyPref",
  "id-smime-aa-signingCertificate": "id-smime-aa-signingCertificate",
  "id-smime-aa-smimeEncryptCerts": "id-smime-aa-smimeEncryptCerts",
  "id-smime-aa-timeStampToken": "id-smime-aa-timeStampToken",
  "id-smime-aa-ets-sigPolicyId": "id-smime-aa-ets-sigPolicyId",
  "id-smime-aa-ets-commitmentType": "id-smime-aa-ets-commitmentType",
  "id-smime-aa-ets-signerLocation": "id-smime-aa-ets-signerLocation",
  "id-smime-aa-ets-signerAttr": "id-smime-aa-ets-signerAttr",
  "id-smime-aa-ets-otherSigCert": "id-smime-aa-ets-otherSigCert",
  "id-smime-aa-ets-contentTimestamp": "id-smime-aa-ets-contentTimestamp",
  "id-smime-aa-ets-CertificateRefs": "id-smime-aa-ets-CertificateRefs",
  "id-smime-aa-ets-RevocationRefs": "id-smime-aa-ets-RevocationRefs",
  "id-smime-aa-ets-certValues": "id-smime-aa-ets-certValues",
  "id-smime-aa-ets-revocationValues": "id-smime-aa-ets-revocationValues",
  "id-smime-aa-ets-escTimeStamp": "id-smime-aa-ets-escTimeStamp",
  "id-smime-aa-ets-certCRLTimestamp": "id-smime-aa-ets-certCRLTimestamp",
  "id-smime-aa-ets-archiveTimeStamp": "id-smime-aa-ets-archiveTimeStamp",
  "id-smime-aa-signatureType": "id-smime-aa-signatureType",
  "id-smime-aa-dvcs-dvc": "id-smime-aa-dvcs-dvc",
  "id-smime-aa-signingCertificateV2": "id-smime-aa-signingCertificateV2",
  "id-smime-alg-ESDHwith3DES": "id-smime-alg-ESDHwith3DES",
  "id-smime-alg-ESDHwithRC2": "id-smime-alg-ESDHwithRC2",
  "id-smime-alg-3DESwrap": "id-smime-alg-3DESwrap",
  "id-smime-alg-RC2wrap": "id-smime-alg-RC2wrap",
  "id-smime-alg-ESDH": "id-smime-alg-ESDH",
  "id-smime-alg-CMS3DESwrap": "id-smime-alg-CMS3DESwrap",
  "id-smime-alg-CMSRC2wrap": "id-smime-alg-CMSRC2wrap",
  "id-alg-PWRI-KEK": "id-alg-PWRI-KEK",
  "id-smime-cd-ldap": "id-smime-cd-ldap",
  "id-smime-spq-ets-sqt-uri": "id-smime-spq-ets-sqt-uri",
  "id-smime-spq-ets-sqt-unotice": "id-smime-spq-ets-sqt-unotice",
  "id-smime-cti-ets-proofOfOrigin": "id-smime-cti-ets-proofOfOrigin",
  "id-smime-cti-ets-proofOfReceipt": "id-smime-cti-ets-proofOfReceipt",
  "id-smime-cti-ets-proofOfDelivery": "id-smime-cti-ets-proofOfDelivery",
  "id-smime-cti-ets-proofOfSender": "id-smime-cti-ets-proofOfSender",
  "id-smime-cti-ets-proofOfApproval": "id-smime-cti-ets-proofOfApproval",
  "id-smime-cti-ets-proofOfCreation": "id-smime-cti-ets-proofOfCreation",
  "friendlyName": "friendlyName",
  "localKeyID": "localKeyID",
  "Microsoft CSP Name": "CSPName",
  "Microsoft Local Key set": "LocalKeySet",
  "x509Certificate": "x509Certificate",
  "sdsiCertificate": "sdsiCertificate",
  "x509Crl": "x509Crl",
  "pbeWithSHA1And128BitRC4": "PBE-SHA1-RC4-128",
  "pbeWithSHA1And40BitRC4": "PBE-SHA1-RC4-40",
  "pbeWithSHA1And3-KeyTripleDES-CBC": "PBE-SHA1-3DES",
  "pbeWithSHA1And2-KeyTripleDES-CBC": "PBE-SHA1-2DES",
  "pbeWithSHA1And128BitRC2-CBC": "PBE-SHA1-RC2-128",
  "pbeWithSHA1And40BitRC2-CBC": "PBE-SHA1-RC2-40",
  "keyBag": "keyBag",
  "pkcs8ShroudedKeyBag": "pkcs8ShroudedKeyBag",
  "certBag": "certBag",
  "crlBag": "crlBag",
  "secretBag": "secretBag",
  "safeContentsBag": "safeContentsBag",
  "md2": "MD2",
  "md4": "MD4",
  "md5": "MD5",
  "md5-sha1": "MD5-SHA1",
  "hmacWithMD5": "hmacWithMD5",
  "hmacWithSHA1": "hmacWithSHA1",
  "sm2": "SM2",
  "sm3": "SM3",
  "sm3WithRSAEncryption": "RSA-SM3",
  "hmacWithSHA224": "hmacWithSHA224",
  "hmacWithSHA256": "hmacWithSHA256",
  "hmacWithSHA384": "hmacWithSHA384",
  "hmacWithSHA512": "hmacWithSHA512",
  "hmacWithSHA512-224": "hmacWithSHA512-224",
  "hmacWithSHA512-256": "hmacWithSHA512-256",
  "rc2-cbc": "RC2-CBC",
  "rc2-ecb": "RC2-ECB",
  "rc2-cfb": "RC2-CFB",
  "rc2-ofb": "RC2-OFB",
  "rc2-40-cbc": "RC2-40-CBC",
  "rc2-64-cbc": "RC2-64-CBC",
  "rc4": "RC4",
  "rc4-40": "RC4-40",
  "des-ede3-cbc": "DES-EDE3-CBC",
  "rc5-cbc": "RC5-CBC",
  "rc5-ecb": "RC5-ECB",
  "rc5-cfb": "RC5-CFB",
  "rc5-ofb": "RC5-OFB",
  "Microsoft Extension Request": "msExtReq",
  "Microsoft Individual Code Signing": "msCodeInd",
  "Microsoft Commercial Code Signing": "msCodeCom",
  "Microsoft Trust List Signing": "msCTLSign",
  "Microsoft Server Gated Crypto": "msSGC",
  "Microsoft Encrypted File System": "msEFS",
  "Microsoft Smartcard Login": "msSmartcardLogin",
  "Microsoft User Principal Name": "msUPN",
  "idea-cbc": "IDEA-CBC",
  "idea-ecb": "IDEA-ECB",
  "idea-cfb": "IDEA-CFB",
  "idea-ofb": "IDEA-OFB",
  "bf-cbc": "BF-CBC",
  "bf-ecb": "BF-ECB",
  "bf-cfb": "BF-CFB",
  "bf-ofb": "BF-OFB",
  "PKIX": "PKIX",
  "id-pkix-mod": "id-pkix-mod",
  "id-pe": "id-pe",
  "id-qt": "id-qt",
  "id-kp": "id-kp",
  "id-it": "id-it",
  "id-pkip": "id-pkip",
  "id-alg": "id-alg",
  "id-cmc": "id-cmc",
  "id-on": "id-on",
  "id-pda": "id-pda",
  "id-aca": "id-aca",
  "id-qcs": "id-qcs",
  "id-cct": "id-cct",
  "id-ppl": "id-ppl",
  "id-ad": "id-ad",
  "id-pkix1-explicit-88": "id-pkix1-explicit-88",
  "id-pkix1-implicit-88": "id-pkix1-implicit-88",
  "id-pkix1-explicit-93": "id-pkix1-explicit-93",
  "id-pkix1-implicit-93": "id-pkix1-implicit-93",
  "id-mod-crmf": "id-mod-crmf",
  "id-mod-cmc": "id-mod-cmc",
  "id-mod-kea-profile-88": "id-mod-kea-profile-88",
  "id-mod-kea-profile-93": "id-mod-kea-profile-93",
  "id-mod-cmp": "id-mod-cmp",
  "id-mod-qualified-cert-88": "id-mod-qualified-cert-88",
  "id-mod-qualified-cert-93": "id-mod-qualified-cert-93",
  "id-mod-attribute-cert": "id-mod-attribute-cert",
  "id-mod-timestamp-protocol": "id-mod-timestamp-protocol",
  "id-mod-ocsp": "id-mod-ocsp",
  "id-mod-dvcs": "id-mod-dvcs",
  "id-mod-cmp2000": "id-mod-cmp2000",
  "Authority Information Access": "authorityInfoAccess",
  "Biometric Info": "biometricInfo",
  "qcStatements": "qcStatements",
  "ac-auditEntity": "ac-auditEntity",
  "ac-targeting": "ac-targeting",
  "aaControls": "aaControls",
  "sbgp-ipAddrBlock": "sbgp-ipAddrBlock",
  "sbgp-autonomousSysNum": "sbgp-autonomousSysNum",
  "sbgp-routerIdentifier": "sbgp-routerIdentifier",
  "ac-proxying": "ac-proxying",
  "Subject Information Access": "subjectInfoAccess",
  "Proxy Certificate Information": "proxyCertInfo",
  "TLS Feature": "tlsfeature",
  "Policy Qualifier CPS": "id-qt-cps",
  "Policy Qualifier User Notice": "id-qt-unotice",
  "textNotice": "textNotice",
  "TLS Web Server Authentication": "serverAuth",
  "TLS Web Client Authentication": "clientAuth",
  "Code Signing": "codeSigning",
  "E-mail Protection": "emailProtection",
  "IPSec End System": "ipsecEndSystem",
  "IPSec Tunnel": "ipsecTunnel",
  "IPSec User": "ipsecUser",
  "Time Stamping": "timeStamping",
  "OCSP Signing": "OCSPSigning",
  "dvcs": "DVCS",
  "ipsec Internet Key Exchange": "ipsecIKE",
  "Ctrl/provision WAP Access": "capwapAC",
  "Ctrl/Provision WAP Termination": "capwapWTP",
  "SSH Client": "secureShellClient",
  "SSH Server": "secureShellServer",
  "Send Router": "sendRouter",
  "Send Proxied Router": "sendProxiedRouter",
  "Send Owner": "sendOwner",
  "Send Proxied Owner": "sendProxiedOwner",
  "CMC Certificate Authority": "cmcCA",
  "CMC Registration Authority": "cmcRA",
  "id-it-caProtEncCert": "id-it-caProtEncCert",
  "id-it-signKeyPairTypes": "id-it-signKeyPairTypes",
  "id-it-encKeyPairTypes": "id-it-encKeyPairTypes",
  "id-it-preferredSymmAlg": "id-it-preferredSymmAlg",
  "id-it-caKeyUpdateInfo": "id-it-caKeyUpdateInfo",
  "id-it-currentCRL": "id-it-currentCRL",
  "id-it-unsupportedOIDs": "id-it-unsupportedOIDs",
  "id-it-subscriptionRequest": "id-it-subscriptionRequest",
  "id-it-subscriptionResponse": "id-it-subscriptionResponse",
  "id-it-keyPairParamReq": "id-it-keyPairParamReq",
  "id-it-keyPairParamRep": "id-it-keyPairParamRep",
  "id-it-revPassphrase": "id-it-revPassphrase",
  "id-it-implicitConfirm": "id-it-implicitConfirm",
  "id-it-confirmWaitTime": "id-it-confirmWaitTime",
  "id-it-origPKIMessage": "id-it-origPKIMessage",
  "id-it-suppLangTags": "id-it-suppLangTags",
  "id-regCtrl": "id-regCtrl",
  "id-regInfo": "id-regInfo",
  "id-regCtrl-regToken": "id-regCtrl-regToken",
  "id-regCtrl-authenticator": "id-regCtrl-authenticator",
  "id-regCtrl-pkiPublicationInfo": "id-regCtrl-pkiPublicationInfo",
  "id-regCtrl-pkiArchiveOptions": "id-regCtrl-pkiArchiveOptions",
  "id-regCtrl-oldCertID": "id-regCtrl-oldCertID",
  "id-regCtrl-protocolEncrKey": "id-regCtrl-protocolEncrKey",
  "id-regInfo-utf8Pairs": "id-regInfo-utf8Pairs",
  "id-regInfo-certReq": "id-regInfo-certReq",
  "id-alg-des40": "id-alg-des40",
  "id-alg-noSignature": "id-alg-noSignature",
  "id-alg-dh-sig-hmac-sha1": "id-alg-dh-sig-hmac-sha1",
  "id-alg-dh-pop": "id-alg-dh-pop",
  "id-cmc-statusInfo": "id-cmc-statusInfo",
  "id-cmc-identification": "id-cmc-identification",
  "id-cmc-identityProof": "id-cmc-identityProof",
  "id-cmc-dataReturn": "id-cmc-dataReturn",
  "id-cmc-transactionId": "id-cmc-transactionId",
  "id-cmc-senderNonce": "id-cmc-senderNonce",
  "id-cmc-recipientNonce": "id-cmc-recipientNonce",
  "id-cmc-addExtensions": "id-cmc-addExtensions",
  "id-cmc-encryptedPOP": "id-cmc-encryptedPOP",
  "id-cmc-decryptedPOP": "id-cmc-decryptedPOP",
  "id-cmc-lraPOPWitness": "id-cmc-lraPOPWitness",
  "id-cmc-getCert": "id-cmc-getCert",
  "id-cmc-getCRL": "id-cmc-getCRL",
  "id-cmc-revokeRequest": "id-cmc-revokeRequest",
  "id-cmc-regInfo": "id-cmc-regInfo",
  "id-cmc-responseInfo": "id-cmc-responseInfo",
  "id-cmc-queryPending": "id-cmc-queryPending",
  "id-cmc-popLinkRandom": "id-cmc-popLinkRandom",
  "id-cmc-popLinkWitness": "id-cmc-popLinkWitness",
  "id-cmc-confirmCertAcceptance": "id-cmc-confirmCertAcceptance",
  "id-on-personalData": "id-on-personalData",
  "Permanent Identifier": "id-on-permanentIdentifier",
  "id-pda-dateOfBirth": "id-pda-dateOfBirth",
  "id-pda-placeOfBirth": "id-pda-placeOfBirth",
  "id-pda-gender": "id-pda-gender",
  "id-pda-countryOfCitizenship": "id-pda-countryOfCitizenship",
  "id-pda-countryOfResidence": "id-pda-countryOfResidence",
  "id-aca-authenticationInfo": "id-aca-authenticationInfo",
  "id-aca-accessIdentity": "id-aca-accessIdentity",
  "id-aca-chargingIdentity": "id-aca-chargingIdentity",
  "id-aca-group": "id-aca-group",
  "id-aca-role": "id-aca-role",
  "id-aca-encAttrs": "id-aca-encAttrs",
  "id-qcs-pkixQCSyntax-v1": "id-qcs-pkixQCSyntax-v1",
  "id-cct-crs": "id-cct-crs",
  "id-cct-PKIData": "id-cct-PKIData",
  "id-cct-PKIResponse": "id-cct-PKIResponse",
  "Any language": "id-ppl-anyLanguage",
  "Inherit all": "id-ppl-inheritAll",
  "Independent": "id-ppl-independent",
  "OCSP": "OCSP",
  "CA Issuers": "caIssuers",
  "AD Time Stamping": "ad_timestamping",
  "ad dvcs": "AD_DVCS",
  "CA Repository": "caRepository",
  "Basic OCSP Response": "basicOCSPResponse",
  "OCSP Nonce": "Nonce",
  "OCSP CRL ID": "CrlID",
  "Acceptable OCSP Responses": "acceptableResponses",
  "OCSP No Check": "noCheck",
  "OCSP Archive Cutoff": "archiveCutoff",
  "OCSP Service Locator": "serviceLocator",
  "Extended OCSP Status": "extendedStatus",
  "valid": "valid",
  "path": "path",
  "Trust Root": "trustRoot",
  "algorithm": "algorithm",
  "md5WithRSA": "RSA-NP-MD5",
  "des-ecb": "DES-ECB",
  "des-cbc": "DES-CBC",
  "des-ofb": "DES-OFB",
  "des-cfb": "DES-CFB",
  "rsaSignature": "rsaSignature",
  "dsaEncryption-old": "DSA-old",
  "dsaWithSHA": "DSA-SHA",
  "shaWithRSAEncryption": "RSA-SHA",
  "des-ede": "DES-EDE",
  "des-ede3": "DES-EDE3",
  "des-ede-cbc": "DES-EDE-CBC",
  "des-ede-cfb": "DES-EDE-CFB",
  "des-ede3-cfb": "DES-EDE3-CFB",
  "des-ede-ofb": "DES-EDE-OFB",
  "des-ede3-ofb": "DES-EDE3-OFB",
  "desx-cbc": "DESX-CBC",
  "sha": "SHA",
  "sha1": "SHA1",
  "dsaWithSHA1-old": "DSA-SHA1-old",
  "sha1WithRSA": "RSA-SHA1-2",
  "ripemd160": "RIPEMD160",
  "ripemd160WithRSA": "RSA-RIPEMD160",
  "blake2b512": "BLAKE2b512",
  "blake2s256": "BLAKE2s256",
  "Strong Extranet ID": "SXNetID",
  "directory services (X.500)": "X500",
  "X509": "X509",
  "commonName": "CN",
  "surname": "SN",
  "serialNumber": "serialNumber",
  "countryName": "C",
  "localityName": "L",
  "stateOrProvinceName": "ST",
  "streetAddress": "street",
  "organizationName": "O",
  "organizationalUnitName": "OU",
  "title": "title",
  "description": "description",
  "searchGuide": "searchGuide",
  "businessCategory": "businessCategory",
  "postalAddress": "postalAddress",
  "postalCode": "postalCode",
  "postOfficeBox": "postOfficeBox",
  "physicalDeliveryOfficeName": "physicalDeliveryOfficeName",
  "telephoneNumber": "telephoneNumber",
  "telexNumber": "telexNumber",
  "teletexTerminalIdentifier": "teletexTerminalIdentifier",
  "facsimileTelephoneNumber": "facsimileTelephoneNumber",
  "x121Address": "x121Address",
  "internationaliSDNNumber": "internationaliSDNNumber",
  "registeredAddress": "registeredAddress",
  "destinationIndicator": "destinationIndicator",
  "preferredDeliveryMethod": "preferredDeliveryMethod",
  "presentationAddress": "presentationAddress",
  "supportedApplicationContext": "supportedApplicationContext",
  "": "dmdName",
  "roleOccupant": "roleOccupant",
  "userPassword": "userPassword",
  "userCertificate": "userCertificate",
  "cACertificate": "cACertificate",
  "authorityRevocationList": "authorityRevocationList",
  "certificateRevocationList": "certificateRevocationList",
  "crossCertificatePair": "crossCertificatePair",
  "name": "name",
  "givenName": "GN",
  "initials": "initials",
  "generationQualifier": "generationQualifier",
  "x500UniqueIdentifier": "x500UniqueIdentifier",
  "dnQualifier": "dnQualifier",
  "enhancedSearchGuide": "enhancedSearchGuide",
  "protocolInformation": "protocolInformation",
  "distinguishedName": "distinguishedName",
  "uniqueMember": "uniqueMember",
  "houseIdentifier": "houseIdentifier",
  "supportedAlgorithms": "supportedAlgorithms",
  "deltaRevocationList": "deltaRevocationList",
  "pseudonym": "pseudonym",
  "role": "role",
  "organizationIdentifier": "organizationIdentifier",
  "countryCode3c": "c3",
  "countryCode3n": "n3",
  "dnsName": "dnsName",
  "directory services - algorithms": "X500algorithms",
  "rsa": "RSA",
  "mdc2WithRSA": "RSA-MDC2",
  "mdc2": "MDC2",
  "id-ce": "id-ce",
  "X509v3 Subject Directory Attributes": "subjectDirectoryAttributes",
  "X509v3 Subject Key Identifier": "subjectKeyIdentifier",
  "X509v3 Key Usage": "keyUsage",
  "X509v3 Private Key Usage Period": "privateKeyUsagePeriod",
  "X509v3 Subject Alternative Name": "subjectAltName",
  "X509v3 Issuer Alternative Name": "issuerAltName",
  "X509v3 Basic Constraints": "basicConstraints",
  "X509v3 CRL Number": "crlNumber",
  "X509v3 CRL Reason Code": "CRLReason",
  "Invalidity Date": "invalidityDate",
  "X509v3 Delta CRL Indicator": "deltaCRL",
  "X509v3 Issuing Distribution Point": "issuingDistributionPoint",
  "X509v3 Certificate Issuer": "certificateIssuer",
  "X509v3 Name Constraints": "nameConstraints",
  "X509v3 CRL Distribution Points": "crlDistributionPoints",
  "X509v3 Certificate Policies": "certificatePolicies",
  "X509v3 Any Policy": "anyPolicy",
  "X509v3 Policy Mappings": "policyMappings",
  "X509v3 Authority Key Identifier": "authorityKeyIdentifier",
  "X509v3 Policy Constraints": "policyConstraints",
  "X509v3 Extended Key Usage": "extendedKeyUsage",
  "X509v3 Freshest CRL": "freshestCRL",
  "X509v3 Inhibit Any Policy": "inhibitAnyPolicy",
  "X509v3 AC Targeting": "targetInformation",
  "X509v3 No Revocation Available": "noRevAvail",
  "Any Extended Key Usage": "anyExtendedKeyUsage",
  "Netscape Communications Corp.": "Netscape",
  "Netscape Certificate Extension": "nsCertExt",
  "Netscape Data Type": "nsDataType",
  "Netscape Cert Type": "nsCertType",
  "Netscape Base Url": "nsBaseUrl",
  "Netscape Revocation Url": "nsRevocationUrl",
  "Netscape CA Revocation Url": "nsCaRevocationUrl",
  "Netscape Renewal Url": "nsRenewalUrl",
  "Netscape CA Policy Url": "nsCaPolicyUrl",
  "Netscape SSL Server Name": "nsSslServerName",
  "Netscape Comment": "nsComment",
  "Netscape Certificate Sequence": "nsCertSequence",
  "Netscape Server Gated Crypto": "nsSGC",
  "org": "ORG",
  "dod": "DOD",
  "iana": "IANA",
  "Directory": "directory",
  "Management": "mgmt",
  "Experimental": "experimental",
  "Private": "private",
  "Security": "security",
  "SNMPv2": "snmpv2",
  "Mail": "Mail",
  "Enterprises": "enterprises",
  "dcObject": "dcobject",
  "MIME MHS": "mime-mhs",
  "mime-mhs-headings": "mime-mhs-headings",
  "mime-mhs-bodies": "mime-mhs-bodies",
  "id-hex-partial-message": "id-hex-partial-message",
  "id-hex-multipart-message": "id-hex-multipart-message",
  "zlib compression": "ZLIB",
  "aes-128-ecb": "AES-128-ECB",
  "aes-128-cbc": "AES-128-CBC",
  "aes-128-ofb": "AES-128-OFB",
  "aes-128-cfb": "AES-128-CFB",
  "id-aes128-wrap": "id-aes128-wrap",
  "aes-128-gcm": "id-aes128-GCM",
  "aes-128-ccm": "id-aes128-CCM",
  "id-aes128-wrap-pad": "id-aes128-wrap-pad",
  "aes-192-ecb": "AES-192-ECB",
  "aes-192-cbc": "AES-192-CBC",
  "aes-192-ofb": "AES-192-OFB",
  "aes-192-cfb": "AES-192-CFB",
  "id-aes192-wrap": "id-aes192-wrap",
  "aes-192-gcm": "id-aes192-GCM",
  "aes-192-ccm": "id-aes192-CCM",
  "id-aes192-wrap-pad": "id-aes192-wrap-pad",
  "aes-256-ecb": "AES-256-ECB",
  "aes-256-cbc": "AES-256-CBC",
  "aes-256-ofb": "AES-256-OFB",
  "aes-256-cfb": "AES-256-CFB",
  "id-aes256-wrap": "id-aes256-wrap",
  "aes-256-gcm": "id-aes256-GCM",
  "aes-256-ccm": "id-aes256-CCM",
  "id-aes256-wrap-pad": "id-aes256-wrap-pad",
  "aes-128-xts": "AES-128-XTS",
  "aes-256-xts": "AES-256-XTS",
  "aes-128-cfb1": "AES-128-CFB1",
  "aes-192-cfb1": "AES-192-CFB1",
  "aes-256-cfb1": "AES-256-CFB1",
  "aes-128-cfb8": "AES-128-CFB8",
  "aes-192-cfb8": "AES-192-CFB8",
  "aes-256-cfb8": "AES-256-CFB8",
  "aes-128-ctr": "AES-128-CTR",
  "aes-192-ctr": "AES-192-CTR",
  "aes-256-ctr": "AES-256-CTR",
  "aes-128-ocb": "AES-128-OCB",
  "aes-192-ocb": "AES-192-OCB",
  "aes-256-ocb": "AES-256-OCB",
  "des-cfb1": "DES-CFB1",
  "des-cfb8": "DES-CFB8",
  "des-ede3-cfb1": "DES-EDE3-CFB1",
  "des-ede3-cfb8": "DES-EDE3-CFB8",
  "sha256": "SHA256",
  "sha384": "SHA384",
  "sha512": "SHA512",
  "sha224": "SHA224",
  "sha512-224": "SHA512-224",
  "sha512-256": "SHA512-256",
  "sha3-224": "SHA3-224",
  "sha3-256": "SHA3-256",
  "sha3-384": "SHA3-384",
  "sha3-512": "SHA3-512",
  "shake128": "SHAKE128",
  "shake256": "SHAKE256",
  "hmac-sha3-224": "id-hmacWithSHA3-224",
  "hmac-sha3-256": "id-hmacWithSHA3-256",
  "hmac-sha3-384": "id-hmacWithSHA3-384",
  "hmac-sha3-512": "id-hmacWithSHA3-512",
  "dsa_with_SHA224": "dsa_with_SHA224",
  "dsa_with_SHA256": "dsa_with_SHA256",
  "dsa_with_SHA384": "id-dsa-with-sha384",
  "dsa_with_SHA512": "id-dsa-with-sha512",
  "dsa_with_SHA3-224": "id-dsa-with-sha3-224",
  "dsa_with_SHA3-256": "id-dsa-with-sha3-256",
  "dsa_with_SHA3-384": "id-dsa-with-sha3-384",
  "dsa_with_SHA3-512": "id-dsa-with-sha3-512",
  "ecdsa_with_SHA3-224": "id-ecdsa-with-sha3-224",
  "ecdsa_with_SHA3-256": "id-ecdsa-with-sha3-256",
  "ecdsa_with_SHA3-384": "id-ecdsa-with-sha3-384",
  "ecdsa_with_SHA3-512": "id-ecdsa-with-sha3-512",
  "RSA-SHA3-224": "id-rsassa-pkcs1-v1_5-with-sha3-224",
  "RSA-SHA3-256": "id-rsassa-pkcs1-v1_5-with-sha3-256",
  "RSA-SHA3-384": "id-rsassa-pkcs1-v1_5-with-sha3-384",
  "RSA-SHA3-512": "id-rsassa-pkcs1-v1_5-with-sha3-512",
  "Hold Instruction Code": "holdInstructionCode",
  "Hold Instruction None": "holdInstructionNone",
  "Hold Instruction Call Issuer": "holdInstructionCallIssuer",
  "Hold Instruction Reject": "holdInstructionReject",
  "data": "data",
  "pss": "pss",
  "ucl": "ucl",
  "pilot": "pilot",
  "pilotAttributeType": "pilotAttributeType",
  "pilotAttributeSyntax": "pilotAttributeSyntax",
  "pilotObjectClass": "pilotObjectClass",
  "pilotGroups": "pilotGroups",
  "iA5StringSyntax": "iA5StringSyntax",
  "caseIgnoreIA5StringSyntax": "caseIgnoreIA5StringSyntax",
  "pilotObject": "pilotObject",
  "pilotPerson": "pilotPerson",
  "account": "account",
  "document": "document",
  "room": "room",
  "documentSeries": "documentSeries",
  "Domain": "domain",
  "rFC822localPart": "rFC822localPart",
  "dNSDomain": "dNSDomain",
  "domainRelatedObject": "domainRelatedObject",
  "friendlyCountry": "friendlyCountry",
  "simpleSecurityObject": "simpleSecurityObject",
  "pilotOrganization": "pilotOrganization",
  "pilotDSA": "pilotDSA",
  "qualityLabelledData": "qualityLabelledData",
  "userId": "UID",
  "textEncodedORAddress": "textEncodedORAddress",
  "rfc822Mailbox": "mail",
  "info": "info",
  "favouriteDrink": "favouriteDrink",
  "roomNumber": "roomNumber",
  "photo": "photo",
  "userClass": "userClass",
  "host": "host",
  "manager": "manager",
  "documentIdentifier": "documentIdentifier",
  "documentTitle": "documentTitle",
  "documentVersion": "documentVersion",
  "documentAuthor": "documentAuthor",
  "documentLocation": "documentLocation",
  "homeTelephoneNumber": "homeTelephoneNumber",
  "secretary": "secretary",
  "otherMailbox": "otherMailbox",
  "lastModifiedTime": "lastModifiedTime",
  "lastModifiedBy": "lastModifiedBy",
  "domainComponent": "DC",
  "aRecord": "aRecord",
  "pilotAttributeType27": "pilotAttributeType27",
  "mXRecord": "mXRecord",
  "nSRecord": "nSRecord",
  "sOARecord": "sOARecord",
  "cNAMERecord": "cNAMERecord",
  "associatedDomain": "associatedDomain",
  "associatedName": "associatedName",
  "homePostalAddress": "homePostalAddress",
  "personalTitle": "personalTitle",
  "mobileTelephoneNumber": "mobileTelephoneNumber",
  "pagerTelephoneNumber": "pagerTelephoneNumber",
  "friendlyCountryName": "friendlyCountryName",
  "uniqueIdentifier": "uid",
  "organizationalStatus": "organizationalStatus",
  "janetMailbox": "janetMailbox",
  "mailPreferenceOption": "mailPreferenceOption",
  "buildingName": "buildingName",
  "dSAQuality": "dSAQuality",
  "singleLevelQuality": "singleLevelQuality",
  "subtreeMinimumQuality": "subtreeMinimumQuality",
  "subtreeMaximumQuality": "subtreeMaximumQuality",
  "personalSignature": "personalSignature",
  "dITRedirect": "dITRedirect",
  "audio": "audio",
  "documentPublisher": "documentPublisher",
  "Secure Electronic Transactions": "id-set",
  "content types": "set-ctype",
  "message extensions": "set-msgExt",
  "set-attr": "set-attr",
  "set-policy": "set-policy",
  "certificate extensions": "set-certExt",
  "set-brand": "set-brand",
  "setct-PANData": "setct-PANData",
  "setct-PANToken": "setct-PANToken",
  "setct-PANOnly": "setct-PANOnly",
  "setct-OIData": "setct-OIData",
  "setct-PI": "setct-PI",
  "setct-PIData": "setct-PIData",
  "setct-PIDataUnsigned": "setct-PIDataUnsigned",
  "setct-HODInput": "setct-HODInput",
  "setct-AuthResBaggage": "setct-AuthResBaggage",
  "setct-AuthRevReqBaggage": "setct-AuthRevReqBaggage",
  "setct-AuthRevResBaggage": "setct-AuthRevResBaggage",
  "setct-CapTokenSeq": "setct-CapTokenSeq",
  "setct-PInitResData": "setct-PInitResData",
  "setct-PI-TBS": "setct-PI-TBS",
  "setct-PResData": "setct-PResData",
  "setct-AuthReqTBS": "setct-AuthReqTBS",
  "setct-AuthResTBS": "setct-AuthResTBS",
  "setct-AuthResTBSX": "setct-AuthResTBSX",
  "setct-AuthTokenTBS": "setct-AuthTokenTBS",
  "setct-CapTokenData": "setct-CapTokenData",
  "setct-CapTokenTBS": "setct-CapTokenTBS",
  "setct-AcqCardCodeMsg": "setct-AcqCardCodeMsg",
  "setct-AuthRevReqTBS": "setct-AuthRevReqTBS",
  "setct-AuthRevResData": "setct-AuthRevResData",
  "setct-AuthRevResTBS": "setct-AuthRevResTBS",
  "setct-CapReqTBS": "setct-CapReqTBS",
  "setct-CapReqTBSX": "setct-CapReqTBSX",
  "setct-CapResData": "setct-CapResData",
  "setct-CapRevReqTBS": "setct-CapRevReqTBS",
  "setct-CapRevReqTBSX": "setct-CapRevReqTBSX",
  "setct-CapRevResData": "setct-CapRevResData",
  "setct-CredReqTBS": "setct-CredReqTBS",
  "setct-CredReqTBSX": "setct-CredReqTBSX",
  "setct-CredResData": "setct-CredResData",
  "setct-CredRevReqTBS": "setct-CredRevReqTBS",
  "setct-CredRevReqTBSX": "setct-CredRevReqTBSX",
  "setct-CredRevResData": "setct-CredRevResData",
  "setct-PCertReqData": "setct-PCertReqData",
  "setct-PCertResTBS": "setct-PCertResTBS",
  "setct-BatchAdminReqData": "setct-BatchAdminReqData",
  "setct-BatchAdminResData": "setct-BatchAdminResData",
  "setct-CardCInitResTBS": "setct-CardCInitResTBS",
  "setct-MeAqCInitResTBS": "setct-MeAqCInitResTBS",
  "setct-RegFormResTBS": "setct-RegFormResTBS",
  "setct-CertReqData": "setct-CertReqData",
  "setct-CertReqTBS": "setct-CertReqTBS",
  "setct-CertResData": "setct-CertResData",
  "setct-CertInqReqTBS": "setct-CertInqReqTBS",
  "setct-ErrorTBS": "setct-ErrorTBS",
  "setct-PIDualSignedTBE": "setct-PIDualSignedTBE",
  "setct-PIUnsignedTBE": "setct-PIUnsignedTBE",
  "setct-AuthReqTBE": "setct-AuthReqTBE",
  "setct-AuthResTBE": "setct-AuthResTBE",
  "setct-AuthResTBEX": "setct-AuthResTBEX",
  "setct-AuthTokenTBE": "setct-AuthTokenTBE",
  "setct-CapTokenTBE": "setct-CapTokenTBE",
  "setct-CapTokenTBEX": "setct-CapTokenTBEX",
  "setct-AcqCardCodeMsgTBE": "setct-AcqCardCodeMsgTBE",
  "setct-AuthRevReqTBE": "setct-AuthRevReqTBE",
  "setct-AuthRevResTBE": "setct-AuthRevResTBE",
  "setct-AuthRevResTBEB": "setct-AuthRevResTBEB",
  "setct-CapReqTBE": "setct-CapReqTBE",
  "setct-CapReqTBEX": "setct-CapReqTBEX",
  "setct-CapResTBE": "setct-CapResTBE",
  "setct-CapRevReqTBE": "setct-CapRevReqTBE",
  "setct-CapRevReqTBEX": "setct-CapRevReqTBEX",
  "setct-CapRevResTBE": "setct-CapRevResTBE",
  "setct-CredReqTBE": "setct-CredReqTBE",
  "setct-CredReqTBEX": "setct-CredReqTBEX",
  "setct-CredResTBE": "setct-CredResTBE",
  "setct-CredRevReqTBE": "setct-CredRevReqTBE",
  "setct-CredRevReqTBEX": "setct-CredRevReqTBEX",
  "setct-CredRevResTBE": "setct-CredRevResTBE",
  "setct-BatchAdminReqTBE": "setct-BatchAdminReqTBE",
  "setct-BatchAdminResTBE": "setct-BatchAdminResTBE",
  "setct-RegFormReqTBE": "setct-RegFormReqTBE",
  "setct-CertReqTBE": "setct-CertReqTBE",
  "setct-CertReqTBEX": "setct-CertReqTBEX",
  "setct-CertResTBE": "setct-CertResTBE",
  "setct-CRLNotificationTBS": "setct-CRLNotificationTBS",
  "setct-CRLNotificationResTBS": "setct-CRLNotificationResTBS",
  "setct-BCIDistributionTBS": "setct-BCIDistributionTBS",
  "generic cryptogram": "setext-genCrypt",
  "merchant initiated auth": "setext-miAuth",
  "setext-pinSecure": "setext-pinSecure",
  "setext-pinAny": "setext-pinAny",
  "setext-track2": "setext-track2",
  "additional verification": "setext-cv",
  "set-policy-root": "set-policy-root",
  "setCext-hashedRoot": "setCext-hashedRoot",
  "setCext-certType": "setCext-certType",
  "setCext-merchData": "setCext-merchData",
  "setCext-cCertRequired": "setCext-cCertRequired",
  "setCext-tunneling": "setCext-tunneling",
  "setCext-setExt": "setCext-setExt",
  "setCext-setQualf": "setCext-setQualf",
  "setCext-PGWYcapabilities": "setCext-PGWYcapabilities",
  "setCext-TokenIdentifier": "setCext-TokenIdentifier",
  "setCext-Track2Data": "setCext-Track2Data",
  "setCext-TokenType": "setCext-TokenType",
  "setCext-IssuerCapabilities": "setCext-IssuerCapabilities",
  "setAttr-Cert": "setAttr-Cert",
  "payment gateway capabilities": "setAttr-PGWYcap",
  "setAttr-TokenType": "setAttr-TokenType",
  "issuer capabilities": "setAttr-IssCap",
  "set-rootKeyThumb": "set-rootKeyThumb",
  "set-addPolicy": "set-addPolicy",
  "setAttr-Token-EMV": "setAttr-Token-EMV",
  "setAttr-Token-B0Prime": "setAttr-Token-B0Prime",
  "setAttr-IssCap-CVM": "setAttr-IssCap-CVM",
  "setAttr-IssCap-T2": "setAttr-IssCap-T2",
  "setAttr-IssCap-Sig": "setAttr-IssCap-Sig",
  "generate cryptogram": "setAttr-GenCryptgrm",
  "encrypted track 2": "setAttr-T2Enc",
  "cleartext track 2": "setAttr-T2cleartxt",
  "ICC or token signature": "setAttr-TokICCsig",
  "secure device signature": "setAttr-SecDevSig",
  "set-brand-IATA-ATA": "set-brand-IATA-ATA",
  "set-brand-Diners": "set-brand-Diners",
  "set-brand-AmericanExpress": "set-brand-AmericanExpress",
  "set-brand-JCB": "set-brand-JCB",
  "set-brand-Visa": "set-brand-Visa",
  "set-brand-MasterCard": "set-brand-MasterCard",
  "set-brand-Novus": "set-brand-Novus",
  "des-cdmf": "DES-CDMF",
  "rsaOAEPEncryptionSET": "rsaOAEPEncryptionSET",
  "ipsec3": "Oakley-EC2N-3",
  "ipsec4": "Oakley-EC2N-4",
  "whirlpool": "whirlpool",
  "cryptopro": "cryptopro",
  "cryptocom": "cryptocom",
  "id-tc26": "id-tc26",
  "GOST R 34.11-94 with GOST R 34.10-2001": "id-GostR3411-94-with-GostR3410-2001",
  "GOST R 34.11-94 with GOST R 34.10-94": "id-GostR3411-94-with-GostR3410-94",
  "GOST R 34.11-94": "md_gost94",
  "HMAC GOST 34.11-94": "id-HMACGostR3411-94",
  "GOST R 34.10-2001": "gost2001",
  "GOST R 34.10-94": "gost94",
  "GOST 28147-89": "gost89",
  "gost89-cnt": "gost89-cnt",
  "gost89-cnt-12": "gost89-cnt-12",
  "gost89-cbc": "gost89-cbc",
  "gost89-ecb": "gost89-ecb",
  "gost89-ctr": "gost89-ctr",
  "GOST 28147-89 MAC": "gost-mac",
  "gost-mac-12": "gost-mac-12",
  "GOST R 34.11-94 PRF": "prf-gostr3411-94",
  "GOST R 34.10-2001 DH": "id-GostR3410-2001DH",
  "GOST R 34.10-94 DH": "id-GostR3410-94DH",
  "id-Gost28147-89-CryptoPro-KeyMeshing": "id-Gost28147-89-CryptoPro-KeyMeshing",
  "id-Gost28147-89-None-KeyMeshing": "id-Gost28147-89-None-KeyMeshing",
  "id-GostR3411-94-TestParamSet": "id-GostR3411-94-TestParamSet",
  "id-GostR3411-94-CryptoProParamSet": "id-GostR3411-94-CryptoProParamSet",
  "id-Gost28147-89-TestParamSet": "id-Gost28147-89-TestParamSet",
  "id-Gost28147-89-CryptoPro-A-ParamSet": "id-Gost28147-89-CryptoPro-A-ParamSet",
  "id-Gost28147-89-CryptoPro-B-ParamSet": "id-Gost28147-89-CryptoPro-B-ParamSet",
  "id-Gost28147-89-CryptoPro-C-ParamSet": "id-Gost28147-89-CryptoPro-C-ParamSet",
  "id-Gost28147-89-CryptoPro-D-ParamSet": "id-Gost28147-89-CryptoPro-D-ParamSet",
  "id-Gost28147-89-CryptoPro-Oscar-1-1-ParamSet": "id-Gost28147-89-CryptoPro-Oscar-1-1-ParamSet",
  "id-Gost28147-89-CryptoPro-Oscar-1-0-ParamSet": "id-Gost28147-89-CryptoPro-Oscar-1-0-ParamSet",
  "id-Gost28147-89-CryptoPro-RIC-1-ParamSet": "id-Gost28147-89-CryptoPro-RIC-1-ParamSet",
  "id-GostR3410-94-TestParamSet": "id-GostR3410-94-TestParamSet",
  "id-GostR3410-94-CryptoPro-A-ParamSet": "id-GostR3410-94-CryptoPro-A-ParamSet",
  "id-GostR3410-94-CryptoPro-B-ParamSet": "id-GostR3410-94-CryptoPro-B-ParamSet",
  "id-GostR3410-94-CryptoPro-C-ParamSet": "id-GostR3410-94-CryptoPro-C-ParamSet",
  "id-GostR3410-94-CryptoPro-D-ParamSet": "id-GostR3410-94-CryptoPro-D-ParamSet",
  "id-GostR3410-94-CryptoPro-XchA-ParamSet": "id-GostR3410-94-CryptoPro-XchA-ParamSet",
  "id-GostR3410-94-CryptoPro-XchB-ParamSet": "id-GostR3410-94-CryptoPro-XchB-ParamSet",
  "id-GostR3410-94-CryptoPro-XchC-ParamSet": "id-GostR3410-94-CryptoPro-XchC-ParamSet",
  "id-GostR3410-2001-TestParamSet": "id-GostR3410-2001-TestParamSet",
  "id-GostR3410-2001-CryptoPro-A-ParamSet": "id-GostR3410-2001-CryptoPro-A-ParamSet",
  "id-GostR3410-2001-CryptoPro-B-ParamSet": "id-GostR3410-2001-CryptoPro-B-ParamSet",
  "id-GostR3410-2001-CryptoPro-C-ParamSet": "id-GostR3410-2001-CryptoPro-C-ParamSet",
  "id-GostR3410-2001-CryptoPro-XchA-ParamSet": "id-GostR3410-2001-CryptoPro-XchA-ParamSet",
  "id-GostR3410-2001-CryptoPro-XchB-ParamSet": "id-GostR3410-2001-CryptoPro-XchB-ParamSet",
  "id-GostR3410-94-a": "id-GostR3410-94-a",
  "id-GostR3410-94-aBis": "id-GostR3410-94-aBis",
  "id-GostR3410-94-b": "id-GostR3410-94-b",
  "id-GostR3410-94-bBis": "id-GostR3410-94-bBis",
  "GOST 28147-89 Cryptocom ParamSet": "id-Gost28147-89-cc",
  "GOST 34.10-94 Cryptocom": "gost94cc",
  "GOST 34.10-2001 Cryptocom": "gost2001cc",
  "GOST R 34.11-94 with GOST R 34.10-94 Cryptocom": "id-GostR3411-94-with-GostR3410-94-cc",
  "GOST R 34.11-94 with GOST R 34.10-2001 Cryptocom": "id-GostR3411-94-with-GostR3410-2001-cc",
  "GOST R 3410-2001 Parameter Set Cryptocom": "id-GostR3410-2001-ParamSet-cc",
  "id-tc26-algorithms": "id-tc26-algorithms",
  "id-tc26-sign": "id-tc26-sign",
  "GOST R 34.10-2012 with 256 bit modulus": "gost2012_256",
  "GOST R 34.10-2012 with 512 bit modulus": "gost2012_512",
  "id-tc26-digest": "id-tc26-digest",
  "GOST R 34.11-2012 with 256 bit hash": "md_gost12_256",
  "GOST R 34.11-2012 with 512 bit hash": "md_gost12_512",
  "id-tc26-signwithdigest": "id-tc26-signwithdigest",
  "GOST R 34.10-2012 with GOST R 34.11-2012 (256 bit)": "id-tc26-signwithdigest-gost3410-2012-256",
  "GOST R 34.10-2012 with GOST R 34.11-2012 (512 bit)": "id-tc26-signwithdigest-gost3410-2012-512",
  "id-tc26-mac": "id-tc26-mac",
  "HMAC GOST 34.11-2012 256 bit": "id-tc26-hmac-gost-3411-2012-256",
  "HMAC GOST 34.11-2012 512 bit": "id-tc26-hmac-gost-3411-2012-512",
  "id-tc26-cipher": "id-tc26-cipher",
  "id-tc26-cipher-gostr3412-2015-magma": "id-tc26-cipher-gostr3412-2015-magma",
  "id-tc26-cipher-gostr3412-2015-magma-ctracpkm": "id-tc26-cipher-gostr3412-2015-magma-ctracpkm",
  "id-tc26-cipher-gostr3412-2015-magma-ctracpkm-omac": "id-tc26-cipher-gostr3412-2015-magma-ctracpkm-omac",
  "id-tc26-cipher-gostr3412-2015-kuznyechik": "id-tc26-cipher-gostr3412-2015-kuznyechik",
  "id-tc26-cipher-gostr3412-2015-kuznyechik-ctracpkm": "id-tc26-cipher-gostr3412-2015-kuznyechik-ctracpkm",
  "id-tc26-cipher-gostr3412-2015-kuznyechik-ctracpkm-omac": "id-tc26-cipher-gostr3412-2015-kuznyechik-ctracpkm-omac",
  "id-tc26-agreement": "id-tc26-agreement",
  "id-tc26-agreement-gost-3410-2012-256": "id-tc26-agreement-gost-3410-2012-256",
  "id-tc26-agreement-gost-3410-2012-512": "id-tc26-agreement-gost-3410-2012-512",
  "id-tc26-wrap": "id-tc26-wrap",
  "id-tc26-wrap-gostr3412-2015-magma": "id-tc26-wrap-gostr3412-2015-magma",
  "id-tc26-wrap-gostr3412-2015-magma-kexp15": "id-tc26-wrap-gostr3412-2015-magma-kexp15",
  "id-tc26-wrap-gostr3412-2015-kuznyechik": "id-tc26-wrap-gostr3412-2015-kuznyechik",
  "id-tc26-wrap-gostr3412-2015-kuznyechik-kexp15": "id-tc26-wrap-gostr3412-2015-kuznyechik-kexp15",
  "id-tc26-constants": "id-tc26-constants",
  "id-tc26-sign-constants": "id-tc26-sign-constants",
  "id-tc26-gost-3410-2012-256-constants": "id-tc26-gost-3410-2012-256-constants",
  "GOST R 34.10-2012 (256 bit) ParamSet A": "id-tc26-gost-3410-2012-256-paramSetA",
  "GOST R 34.10-2012 (256 bit) ParamSet B": "id-tc26-gost-3410-2012-256-paramSetB",
  "GOST R 34.10-2012 (256 bit) ParamSet C": "id-tc26-gost-3410-2012-256-paramSetC",
  "GOST R 34.10-2012 (256 bit) ParamSet D": "id-tc26-gost-3410-2012-256-paramSetD",
  "id-tc26-gost-3410-2012-512-constants": "id-tc26-gost-3410-2012-512-constants",
  "GOST R 34.10-2012 (512 bit) testing parameter set": "id-tc26-gost-3410-2012-512-paramSetTest",
  "GOST R 34.10-2012 (512 bit) ParamSet A": "id-tc26-gost-3410-2012-512-paramSetA",
  "GOST R 34.10-2012 (512 bit) ParamSet B": "id-tc26-gost-3410-2012-512-paramSetB",
  "GOST R 34.10-2012 (512 bit) ParamSet C": "id-tc26-gost-3410-2012-512-paramSetC",
  "id-tc26-digest-constants": "id-tc26-digest-constants",
  "id-tc26-cipher-constants": "id-tc26-cipher-constants",
  "id-tc26-gost-28147-constants": "id-tc26-gost-28147-constants",
  "GOST 28147-89 TC26 parameter set": "id-tc26-gost-28147-param-Z",
  "INN": "INN",
  "OGRN": "OGRN",
  "SNILS": "SNILS",
  "Signing Tool of Subject": "subjectSignTool",
  "Signing Tool of Issuer": "issuerSignTool",
  "grasshopper-ecb": "grasshopper-ecb",
  "grasshopper-ctr": "grasshopper-ctr",
  "grasshopper-ofb": "grasshopper-ofb",
  "grasshopper-cbc": "grasshopper-cbc",
  "grasshopper-cfb": "grasshopper-cfb",
  "grasshopper-mac": "grasshopper-mac",
  "magma-ecb": "magma-ecb",
  "magma-ctr": "magma-ctr",
  "magma-ofb": "magma-ofb",
  "magma-cbc": "magma-cbc",
  "magma-cfb": "magma-cfb",
  "magma-mac": "magma-mac",
  "camellia-128-cbc": "CAMELLIA-128-CBC",
  "camellia-192-cbc": "CAMELLIA-192-CBC",
  "camellia-256-cbc": "CAMELLIA-256-CBC",
  "id-camellia128-wrap": "id-camellia128-wrap",
  "id-camellia192-wrap": "id-camellia192-wrap",
  "id-camellia256-wrap": "id-camellia256-wrap",
  "camellia-128-ecb": "CAMELLIA-128-ECB",
  "camellia-128-ofb": "CAMELLIA-128-OFB",
  "camellia-128-cfb": "CAMELLIA-128-CFB",
  "camellia-128-gcm": "CAMELLIA-128-GCM",
  "camellia-128-ccm": "CAMELLIA-128-CCM",
  "camellia-128-ctr": "CAMELLIA-128-CTR",
  "camellia-128-cmac": "CAMELLIA-128-CMAC",
  "camellia-192-ecb": "CAMELLIA-192-ECB",
  "camellia-192-ofb": "CAMELLIA-192-OFB",
  "camellia-192-cfb": "CAMELLIA-192-CFB",
  "camellia-192-gcm": "CAMELLIA-192-GCM",
  "camellia-192-ccm": "CAMELLIA-192-CCM",
  "camellia-192-ctr": "CAMELLIA-192-CTR",
  "camellia-192-cmac": "CAMELLIA-192-CMAC",
  "camellia-256-ecb": "CAMELLIA-256-ECB",
  "camellia-256-ofb": "CAMELLIA-256-OFB",
  "camellia-256-cfb": "CAMELLIA-256-CFB",
  "camellia-256-gcm": "CAMELLIA-256-GCM",
  "camellia-256-ccm": "CAMELLIA-256-CCM",
  "camellia-256-ctr": "CAMELLIA-256-CTR",
  "camellia-256-cmac": "CAMELLIA-256-CMAC",
  "camellia-128-cfb1": "CAMELLIA-128-CFB1",
  "camellia-192-cfb1": "CAMELLIA-192-CFB1",
  "camellia-256-cfb1": "CAMELLIA-256-CFB1",
  "camellia-128-cfb8": "CAMELLIA-128-CFB8",
  "camellia-192-cfb8": "CAMELLIA-192-CFB8",
  "camellia-256-cfb8": "CAMELLIA-256-CFB8",
  "aria-128-ecb": "ARIA-128-ECB",
  "aria-128-cbc": "ARIA-128-CBC",
  "aria-128-cfb": "ARIA-128-CFB",
  "aria-128-ofb": "ARIA-128-OFB",
  "aria-128-ctr": "ARIA-128-CTR",
  "aria-192-ecb": "ARIA-192-ECB",
  "aria-192-cbc": "ARIA-192-CBC",
  "aria-192-cfb": "ARIA-192-CFB",
  "aria-192-ofb": "ARIA-192-OFB",
  "aria-192-ctr": "ARIA-192-CTR",
  "aria-256-ecb": "ARIA-256-ECB",
  "aria-256-cbc": "ARIA-256-CBC",
  "aria-256-cfb": "ARIA-256-CFB",
  "aria-256-ofb": "ARIA-256-OFB",
  "aria-256-ctr": "ARIA-256-CTR",
  "aria-128-cfb1": "ARIA-128-CFB1",
  "aria-192-cfb1": "ARIA-192-CFB1",
  "aria-256-cfb1": "ARIA-256-CFB1",
  "aria-128-cfb8": "ARIA-128-CFB8",
  "aria-192-cfb8": "ARIA-192-CFB8",
  "aria-256-cfb8": "ARIA-256-CFB8",
  "aria-128-ccm": "ARIA-128-CCM",
  "aria-192-ccm": "ARIA-192-CCM",
  "aria-256-ccm": "ARIA-256-CCM",
  "aria-128-gcm": "ARIA-128-GCM",
  "aria-192-gcm": "ARIA-192-GCM",
  "aria-256-gcm": "ARIA-256-GCM",
  "kisa": "KISA",
  "seed-ecb": "SEED-ECB",
  "seed-cbc": "SEED-CBC",
  "seed-cfb": "SEED-CFB",
  "seed-ofb": "SEED-OFB",
  "sm4-ecb": "SM4-ECB",
  "sm4-cbc": "SM4-CBC",
  "sm4-ofb": "SM4-OFB",
  "sm4-cfb": "SM4-CFB",
  "sm4-cfb1": "SM4-CFB1",
  "sm4-cfb8": "SM4-CFB8",
  "sm4-ctr": "SM4-CTR",
  "hmac": "HMAC",
  "cmac": "CMAC",
  "rc4-hmac-md5": "RC4-HMAC-MD5",
  "aes-128-cbc-hmac-sha1": "AES-128-CBC-HMAC-SHA1",
  "aes-192-cbc-hmac-sha1": "AES-192-CBC-HMAC-SHA1",
  "aes-256-cbc-hmac-sha1": "AES-256-CBC-HMAC-SHA1",
  "aes-128-cbc-hmac-sha256": "AES-128-CBC-HMAC-SHA256",
  "aes-192-cbc-hmac-sha256": "AES-192-CBC-HMAC-SHA256",
  "aes-256-cbc-hmac-sha256": "AES-256-CBC-HMAC-SHA256",
  "chacha20-poly1305": "ChaCha20-Poly1305",
  "chacha20": "ChaCha20",
  "X9.42 DH": "dhpublicnumber",
  "brainpoolP160r1": "brainpoolP160r1",
  "brainpoolP160t1": "brainpoolP160t1",
  "brainpoolP192r1": "brainpoolP192r1",
  "brainpoolP192t1": "brainpoolP192t1",
  "brainpoolP224r1": "brainpoolP224r1",
  "brainpoolP224t1": "brainpoolP224t1",
  "brainpoolP256r1": "brainpoolP256r1",
  "brainpoolP256t1": "brainpoolP256t1",
  "brainpoolP320r1": "brainpoolP320r1",
  "brainpoolP320t1": "brainpoolP320t1",
  "brainpoolP384r1": "brainpoolP384r1",
  "brainpoolP384t1": "brainpoolP384t1",
  "brainpoolP512r1": "brainpoolP512r1",
  "brainpoolP512t1": "brainpoolP512t1",
  "dhSinglePass-stdDH-sha1kdf-scheme": "dhSinglePass-stdDH-sha1kdf-scheme",
  "dhSinglePass-stdDH-sha224kdf-scheme": "dhSinglePass-stdDH-sha224kdf-scheme",
  "dhSinglePass-stdDH-sha256kdf-scheme": "dhSinglePass-stdDH-sha256kdf-scheme",
  "dhSinglePass-stdDH-sha384kdf-scheme": "dhSinglePass-stdDH-sha384kdf-scheme",
  "dhSinglePass-stdDH-sha512kdf-scheme": "dhSinglePass-stdDH-sha512kdf-scheme",
  "dhSinglePass-cofactorDH-sha1kdf-scheme": "dhSinglePass-cofactorDH-sha1kdf-scheme",
  "dhSinglePass-cofactorDH-sha224kdf-scheme": "dhSinglePass-cofactorDH-sha224kdf-scheme",
  "dhSinglePass-cofactorDH-sha256kdf-scheme": "dhSinglePass-cofactorDH-sha256kdf-scheme",
  "dhSinglePass-cofactorDH-sha384kdf-scheme": "dhSinglePass-cofactorDH-sha384kdf-scheme",
  "dhSinglePass-cofactorDH-sha512kdf-scheme": "dhSinglePass-cofactorDH-sha512kdf-scheme",
  "dh-std-kdf": "dh-std-kdf",
  "dh-cofactor-kdf": "dh-cofactor-kdf",
  "CT Precertificate SCTs": "ct_precert_scts",
  "CT Precertificate Poison": "ct_precert_poison",
  "CT Precertificate Signer": "ct_precert_signer",
  "CT Certificate SCTs": "ct_cert_scts",
  "jurisdictionLocalityName": "jurisdictionL",
  "jurisdictionStateOrProvinceName": "jurisdictionST",
  "jurisdictionCountryName": "jurisdictionC",
  "scrypt": "id-scrypt",
  "tls1-prf": "TLS1-PRF",
  "hkdf": "HKDF",
  "id-pkinit": "id-pkinit",
  "PKINIT Client Auth": "pkInitClientAuth",
  "Signing KDC Response": "pkInitKDC",
  "X25519": "X25519",
  "X448": "X448",
  "ED25519": "ED25519",
  "ED448": "ED448",
  "kx-rsa": "KxRSA",
  "kx-ecdhe": "KxECDHE",
  "kx-dhe": "KxDHE",
  "kx-ecdhe-psk": "KxECDHE-PSK",
  "kx-dhe-psk": "KxDHE-PSK",
  "kx-rsa-psk": "KxRSA_PSK",
  "kx-psk": "KxPSK",
  "kx-srp": "KxSRP",
  "kx-gost": "KxGOST",
  "kx-any": "KxANY",
  "auth-rsa": "AuthRSA",
  "auth-ecdsa": "AuthECDSA",
  "auth-psk": "AuthPSK",
  "auth-dss": "AuthDSS",
  "auth-gost01": "AuthGOST01",
  "auth-gost12": "AuthGOST12",
  "auth-srp": "AuthSRP",
  "auth-null": "AuthNULL",
  "auth-any": "AuthANY",
  "poly1305": "Poly1305",
  "siphash": "SipHash",
  "ffdhe2048": "ffdhe2048",
  "ffdhe3072": "ffdhe3072",
  "ffdhe4096": "ffdhe4096",
  "ffdhe6144": "ffdhe6144",
  "ffdhe8192": "ffdhe8192",
  "ISO-UA": "ISO-UA",
  "ua-pki": "ua-pki",
  "DSTU Gost 28147-2009": "dstu28147",
  "DSTU Gost 28147-2009 OFB mode": "dstu28147-ofb",
  "DSTU Gost 28147-2009 CFB mode": "dstu28147-cfb",
  "DSTU Gost 28147-2009 key wrap": "dstu28147-wrap",
  "HMAC DSTU Gost 34311-95": "hmacWithDstu34311",
  "DSTU Gost 34311-95": "dstu34311",
  "DSTU 4145-2002 little endian": "dstu4145le",
  "DSTU 4145-2002 big endian": "dstu4145be",
  "DSTU curve 0": "uacurve0",
  "DSTU curve 1": "uacurve1",
  "DSTU curve 2": "uacurve2",
  "DSTU curve 3": "uacurve3",
  "DSTU curve 4": "uacurve4",
  "DSTU curve 5": "uacurve5",
  "DSTU curve 6": "uacurve6",
  "DSTU curve 7": "uacurve7",
  "DSTU curve 8": "uacurve8",
  "DSTU curve 9": "uacurve9"
}
